import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.cwd(),fixture={version:4,discos:[{id:'one',artista:'Band',titulo:'Album',lista:'coleccion',formato:'CD',tracklist:[],codigoBarras:'12345678'}],borrados:[]};
const server=createServer((req,res)=>{try{let f=path.join(root,new URL(req.url,'http://local').pathname);if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
fs.mkdirSync('visual-results',{recursive:true});
try{for(const width of [390,1440])for(const colorScheme of ['light','dark']){
 const context=await browser.newContext({viewport:{width,height:844},colorScheme,reducedMotion:'reduce',serviceWorkers:'block'});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());
 await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>typeof cargaColeccion!=='undefined'&&cargaColeccion==='auth_required');assert(!await page.locator('#board').innerText().then(t=>t.includes('Tu discoteca está vacía')));assert.equal(await page.evaluate(()=>escrituraSegura(true)),false);
 await page.evaluate(f=>{localStorage.setItem('discoteca.local.v4',JSON.stringify(f));},fixture);await page.reload();await page.waitForSelector('.tile');assert.equal(await page.evaluate(()=>DB.discos.length),1);
 await page.evaluate(f=>{localStorage.setItem('discoteca.lastKnownGood',JSON.stringify(f));localStorage.setItem('discoteca.local.v4','{broken');},fixture);await page.reload();await page.waitForSelector('.tile');assert.equal(await page.evaluate(()=>DB.discos.length),1);
 await page.evaluate(()=>{window.__before=JSON.stringify(DB);window.__resolves=[];resolverTienda=value=>new Promise(resolve=>__resolves.push({value,resolve}));modoTienda();});
 await page.locator('#tCod').fill('first');await page.locator('#tOk').click();await page.locator('#tCod').fill('second');await page.locator('#tOk').click();
 await page.evaluate(()=>__resolves[1].resolve({result:{state:'uncertain',discs:[]}}));await page.waitForFunction(()=>document.querySelector('.tienda').dataset.state==='uncertain');await page.evaluate(()=>__resolves[0].resolve({result:{state:'exact_release',discs:[]}}));assert.equal(await page.locator('.tienda').getAttribute('data-state'),'uncertain');
 await page.screenshot({path:`visual-results/f14-shop-${width}-${colorScheme}.png`});
 await page.keyboard.press('Escape');assert.equal(await page.locator('.tienda').count(),0);assert.equal(await page.evaluate(()=>JSON.stringify(DB)===__before),true);
 // getUserMedia resolves after the dialog closes: all tracks must still stop.
 await page.evaluate(()=>{window.__stopped=0;window.BarcodeDetector=class{detect(){return Promise.resolve([])}};navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>window.__camera=resolve);window.__closeScan=escanear(()=>{});__closeScan();__camera({getTracks:()=>[{stop(){__stopped++}}],getVideoTracks:()=>[]});});await page.waitForFunction(()=>__stopped===1);
 await page.evaluate(()=>{delete window.BarcodeDetector;window.__mediaCalled=false;navigator.mediaDevices.getUserMedia=()=>{__mediaCalled=true;return Promise.reject(Error('unexpected'))};window.__closeScan=escanear(()=>{});});assert.equal(await page.evaluate(()=>__mediaCalled),false);assert(await page.locator('#cbMan').isVisible());await page.evaluate(()=>__closeScan());
 await page.evaluate(()=>verArtista('Band'));assert(await page.getByRole('heading',{name:'Tu colección',exact:true,level:4}).isVisible());assert(await page.getByText('Favoritos olvidados',{exact:true}).isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`visual-results/f14-artist-${width}-${colorScheme}.png`});await page.keyboard.press('Escape');
 assert.deepEqual(errors,[]);await context.close();console.log(`F14 browser ${width} ${colorScheme}: auth, cache, race, late camera, manual fallback, artist and no writes OK`);
}}finally{await browser.close();server.close();}
